### ISSUE TITLE
Missing dot in StackBlitz URL

### ISSUE THREAD

**Issue by aureliendossantos** [withastro/studio-issues#1]
My repo is named `aureliendossantos/aureliendossantos.com`. When I enable the StackBlitz Studio App and click on the link, it brings me to:

```
https://stackblitz.com/~/github.com/aureliendossantos/aureliendossantoscom
```

instead of:

```
https://stackblitz.com/~/github.com/aureliendossantos/aureliendossantos.com
```

**Comment by matthewp** [comment]
This should be fixed now, let me know if not!

**Comment by aureliendossantos** [comment]
@matthewp Sorry, but nothing changed, I reloaded and I still have the same issue.

**Comment by itsMapleLeaf** [comment]
Just gave it a shot now and it seems to work fine, are you still running into this?

**Comment by aureliendossantos** [comment]
Yes, still the same issue.

**Comment by itsMapleLeaf** [comment]
It looks like this was a problem specifically with repos created close to our launch date. It _should_ be addressed now. Let us know if you run into any other issues 🙂
